apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
spec:
  replicas: 1
  serviceName: movie-db
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: {{ .Values.movie_db.image }}
        ports:
        - containerPort: {{ .Values.movie_db.port }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.movie_db.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.movie_db.password }}
        - name: POSTGRES_DB
          value: {{ .Values.movie_db.dbname }}
        volumeMounts:
        - name: movie-db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: movie-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
