apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: {{ .Values.cast_service.image }}
        ports:
        - containerPort: {{ .Values.cast_service.port }}
        env:
        - name: DATABASE_URI
          value: {{ .Values.cast_service.database_uri }}
        command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "{{ .Values.cast_service.port }}"]
