apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: {{ .Values.nginx.port }}
    nodePort: {{ .Values.nginx.nodePort }}
    targetPort: {{ .Values.nginx.port }}
