apiVersion: v1
kind: Service
metadata:
  name: cast-db
spec:
  selector:
    app: cast-db
  ports:
  - protocol: TCP
    port: {{ .Values.cast_db.port }}
    targetPort: {{ .Values.cast_db.port }}
    
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: cast-service
  ports:
  - protocol: TCP
    port: {{ .Values.cast_service.port }}
    targetPort: {{ .Values.cast_service.port }}

