nginx:
  image: nginx:latest
  port: 8080
  nodePort: 30300
  proxyConfig:
    movies:
      path: /api/v1/movies
      service: movie-service
      port: 8000
    casts:
      path: /api/v1/casts
      service: cast-service
      port: 8000

movie_db:
  image: postgres:12.1-alpine
  username: movie_db_username
  password: movie_db_password
  dbname: movie_db_dev
  port: 5432

cast_db:
  image: postgres:12.1-alpine
  username: cast_db_username
  password: cast_db_password
  dbname: cast_db_dev
  port: 5432

cast_service:
  image: sevsachot/jenkinsexam-cast-service:latest
  port: 8000
  database_uri: "postgresql://{{ .Values.cast_db.username }}:{{ .Values.cast_db.password }}@cast-db/{{ .Values.cast_db.dbname }}"

movie_service:
  image: sevsachot/jenkinsexam-movie-service:v1
  port: 8000
  database_uri: "postgresql://{{ .Values.movie_db.username }}:{{ .Values.movie_db.password }}@movie-db/{{ .Values.movie_db.dbname }}"






